name: 'Consumable Code The Sport DB API'
description: 'Retrofit has been Handled, Consumable code for request Public API (TheSportDbApi)'
author: 'Muhammad Faisal Amir'
branding:
  icon: archive
  color: green
inputs:
  myInput:
    description: 'Input to use'
    required: false
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}